name: Deploy Static Index Site to Pages

on:
  push:
    branches: ["main"] # Change to "master" if your default branch uses that name

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
   build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Generate Directory Index Files
        run: node build-index.js

      - name: Deploy to gh-pages Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: assets # The folder containing the files you want on your site
          branch: gh-pages # The branch the action will create and push to
          clean: true # Automatically removes deleted files from the branch